apiVersion: v1
kind: Secret
metadata:
  name: mdm-db-secret
type: Opaque
stringData:
  # 本番ではOCI VaultやKubernetes Secretを使って安全に注入してください
  DATABASE_URL: postgresql://mdm_admin:D4t7HUfA-cKFFvF@10.0.10.50:5432/postgres
